baseURL = "https://www.bytejunkie.dev/"
languageCode = "en-us"
title = "Cloud Platform Engineering, or something approaching it."
theme = "hugo-theme-easybook"

[params]
    author = "Matt Short"
    description = "A blog about cloud based platform engineering, whatever that is."
    avatar = "/bytejunkie.png"

[params.social]
    GitHub = "http://github.com/bytejunkie"
    Email = "mailto:matt@bytejunkie.dev"
    Twitter = "https://twitter.com/bytejunkie"